#!/bin/bash
#
#  bitqubed The bitqube core server.
#
#
# chkconfig: 345 80 20
# description: bitqubed
# processname: bitqubed
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/bitqubed, see below
if [ -f /etc/sysconfig/bitqubed ]; then
        . /etc/sysconfig/bitqubed
fi

RETVAL=0

prog=bitqubed
# you can override the lockfile via BITQUBED_LOCKFILE in /etc/sysconfig/bitqubed
lockfile=${BITQUBED_LOCKFILE-/var/lock/subsys/bitqubed}

# bitqubed defaults to /usr/bin/bitqubed, override with BITQUBED_BIN
bitqubed=${BITQUBED_BIN-/usr/bin/bitqubed}

# bitqubed opts default to -disablewallet, override with BITQUBED_OPTS
bitqubed_opts=${BITQUBED_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $bitqubed $bitqubed_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
