description "BitQube Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env BITQUBED_BIN="/usr/bin/bitqubed"
env BITQUBED_USER="bitqube"
env BITQUBED_GROUP="bitqube"
env BITQUBED_PIDDIR="/var/run/bitqubed"
# upstart can't handle variables constructed with other variables
env BITQUBED_PIDFILE="/var/run/bitqubed/bitqubed.pid"
env BITQUBED_CONFIGFILE="/etc/bitqube/bitqube.conf"
env BITQUBED_DATADIR="/var/lib/bitqubed"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # bitqubed will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$BITQUBED_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run bitqubed."
        echo "The setting must appear in $BITQUBED_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"BitQube Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$BITQUBED_PIDDIR"
    chmod 0755 "$BITQUBED_PIDDIR"
    chown $BITQUBED_USER:$BITQUBED_GROUP "$BITQUBED_PIDDIR"
    chown $BITQUBED_USER:$BITQUBED_GROUP "$BITQUBED_CONFIGFILE"
    chmod 0660 "$BITQUBED_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$BITQUBED_PIDFILE" \
    --chuid $BITQUBED_USER:$BITQUBED_GROUP \
    --exec "$BITQUBED_BIN" \
    -- \
    -pid="$BITQUBED_PIDFILE" \
    -conf="$BITQUBED_CONFIGFILE" \
    -datadir="$BITQUBED_DATADIR" \
    -disablewallet \
    -daemon

